steps:
# Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Run make command
- name: 'gcr.io/cloud-builders/make'
  args: ['build']

# Deploy to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
